name: Python application

on:
  push:
    branches: [ master ]

jobs:
  sync-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python deps
      run: pip install pillow requests
    - name: Run a one-line script
      run: python ./.github/workflows/sync_template.py
    - name: Check changes
      run: git status
    - name: Commit overlay image
      run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -am "Sync overlay image"
          git push
